In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("collected research people.csv")

In [3]:
df.head()

,Unnamed: 0,Nome,Endereerço,Cidade,Estado,phone,anual_income,Estado Civil,AAge,n_filhos,Moradia,Food_restrictions,streaming,diariamente_sun blocker,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [4]:
df = df.drop(columns=['Unnamed: 0'])
df.head()

,Nome,Endereerço,Cidade,Estado,phone,anual_income,Estado Civil,AAge,n_filhos,Moradia,Food_restrictions,streaming,diariamente_sun blocker,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [8]:
novas_colunas = {'Endereerço': 'Endereço',
              'phone': 'Telefone',
              'anual_income': 'Renda Anual',
              'AAge': 'Idade',
              'n_filhos': 'N Filhos',
              'diariamente_sun blocker': 'Usa protetor solar diariamente',
              'Food_restrictions': 'Restrição alimentar',
              'streaming': 'Streaming'
              }

# Insira aqui seu código
#df.rename...
df.rename(columns=novas_colunas, inplace=True)
df.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,N Filhos,Moradia,Restrição alimentar,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

O **\W** equivale a [^a-zA-Zà-úÀ-Ú0-9_].

In [9]:
df.Nome.str.replace('\W', '', regex=True)

0          MariaClaraNovaes
1          DaviLuccaPereira
2            SrCaioCaldeira
3             KaiqueAzevedo
4              PedroMoreira
5         SraAnaJúliaCastro
6             ErickCarvalho
7        SraAnaSophiaVieira
8           Dav4iNascimento
9                JuandaMota
10            StephanyPinto
11             JoanaRezende
12        DraLetíciaRibeiro
13           BeatrizAzevedo
14            AndréMonteiro
15       JoãoGuilhermePorto
16            Augusto_Rocha
17      SrtaIsabellydaRocha
18            HeloísaSantos
19            CalebeAzevedo
20                _AnaAlves
21     MariaFernandaRibeiro
22              SamuelJesus
23             BeatrizRamos
24              DrDaviCunha
25         EnricoCavalcanti
26              RaquelMoura
27            LorenaCardoso
28            DiogoCaldeira
29           MariaGonçalves
30           IsadoraCardoso
31             IgorFerreira
32             SabrinaNunes
33         PedroMiguelSilva
34    DraClaricedaConceição
35          DanielRodrigues
36                IsisSilva
Name: Nome, dtype: object

In [12]:
# Remover caracteres especiais, mantendo letras, números e espaços
df['Nome'] = df['Nome'].str.replace('[^a-zA-Zà-úÀ-Ú0-9 ]', '', regex=True)
df['Nome']

0           Maria Clara Novaes
1           Davi Lucca Pereira
2             Sr Caio Caldeira
3               Kaique Azevedo
4                Pedro Moreira
5         Sra Ana Júlia Castro
6               Erick Carvalho
7        Sra Ana Sophia Vieira
8             Dav4i Nascimento
9                 Juan da Mota
10              Stephany Pinto
11               Joana Rezende
12         Dra Letícia Ribeiro
13             Beatriz Azevedo
14              André Monteiro
15        João Guilherme Porto
16               Augusto Rocha
17      Srta Isabelly da Rocha
18              Heloísa Santos
19              Calebe Azevedo
20                   Ana Alves
21      Maria Fernanda Ribeiro
22                Samuel Jesus
23               Beatriz Ramos
24               Dr Davi Cunha
25           Enrico Cavalcanti
26                Raquel Moura
27              Lorena Cardoso
28              Diogo Caldeira
29             Maria Gonçalves
30             Isadora Cardoso
31               Igor Ferreira
32               Sabrina Nunes
33          Pedro Miguel Silva
34    Dra Clarice da Conceição
35            Daniel Rodrigues
36                  Isis Silva
Name: Nome, dtype: object

In [ ]:
df.head()

,Nome,Endereerço,Cidade,Estado,phone,anual_income,Estado Civil,AAge,n_filhos,Moradia,Food_restrictions,streaming,diariamente_sun blocker,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

Cenário 1:

A empresa Carri Construtora contratou a empresa que você trabalha para encontrar possíveis compradores para o seus novos empreendimentos.

A empresa quer entender as necessidades dos clientes, e quer informações com:

*   Quais cliente devemos abordar;
*   Qual empreendimento nós devemos mostrá-los;
*   Esse cliente está em busca em investir em um imóvel ou comprar para moradia?


 Se renda anual > 104 = pode participar do Minha casa minha vida

In [ ]:
df.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,N Filhos,Moradia,Restrição alimentar,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [ ]:
df_carri = df.copy()

In [23]:
#Excluindo colunas não relevantes para analizar o cenário
#printando todas as colunas 
#df.columns
#dicionario com a lista das colunas
drop_carri = ['Restrição alimentar',
              'Streaming',
              'Usa protetor solar diariamente','Quantidade de Livros Comprados',
              'Autor Favorito']
#dropando colunas
df_carri.drop(columns = drop_carri, inplace=True)
#df_carri.drop(columns)

In [ ]:
#Se renda anual > 104 = pode participar do Minha casa minha vida
#8 mil *13
8*13

In [ ]:
#conferindo renda anual
#df_carri.describe()
#criando coluna chamada Minha Casa Minha Vida 
df_carri['Minha casa minha vida'] = True

#conferindo no print a coluna criada
df_carri.head()

In [ ]:
#Pessoas na coluna Moradia com valores == 'Quitada'-> recebe o valor True e pessoas com valores == 'Financiamento' recebem o valor False
np.where((df_carri.Moradia =='Quitado')| (df_carri.Moradia == 'Financiamento'), True, False)

array([False, False,  True, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True])

In [31]:
#criando variavel investimento que recebe o filtro criado anteriormente
df_carri['Investimento'] = np.where((df_carri.Moradia =='Quitado')| (df_carri.Moradia == 'Financiamento'), True, False)
df_carri.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,N Filhos,Moradia,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,email,Minha casa minha vida,Investimento
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Não,Sim,NaN,mariaclaranovaes285@gemeil.com,True,False
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,Não,Sim,Não,daviluccapereira933@exemplo.com,True,False
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Não,NaN,Sim,srcaiocaldeira626@gemeil.com,True,True
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Não,Não,Sim,kaiqueazevedo731@rotmail.com,True,False
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,Sim,NaN,Sim,pedromoreira622@gemeil.com,True,True

Cenário 2: Uma empresa chamada Hillo, é uma empresa que está estudando o mercado e quer encontrar uma parceria com uma empresa de Streeming (netflix, Disney plus etc), mas gostaria de saber quais as empresas dariam o maior retorno de investimento.
Eles podem fazer análise de machine learning também com esses dados.

In [37]:
#foco na coluna stream
#df.head()
df.columns

Index(['Nome', 'Endereço', 'Cidade', 'Estado', 'Telefone', 'Renda Anual',
       'Estado Civil', 'Idade', 'N Filhos', 'Moradia', 'Restrição alimentar',
       'Streaming', 'Usa protetor solar diariamente',
       'Vai na Praia Mensalmente', 'Faz Academia',
       'Compra e Lê Livros Todos os Anos', 'Quantidade de Livros Comprados',
       'Autor Favorito', 'email'],
      dtype='object')

In [47]:
#copiando as colunas para a variavel df_hillo
df_hillo =df.copy()

#excluir colunas que não são interessantes para análise
df_hillo = df_hillo.drop(columns=['Moradia',
                                  'Restrição alimentar',
                                  'Vai na Praia Mensalmente',
                                  'Usa protetor solar diariamente',
                                  'Faz Academia',
                                  'Compra e Lê Livros Todos os Anos',
                                  'Quantidade de Livros Comprados',
                                  'Autor Favorito'])

In [48]:
df_hillo.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,N Filhos,Streaming,email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Globo Play,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,Todos,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,NaN,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Globo Play,pedromoreira622@gemeil.com

In [49]:
#verificando dados da coluna streaming
df_hillo.Streaming

0           Globo Play
1                Todos
2                  NaN
3                  NaN
4           Globo Play
5        Netflix e HBO
6                  NaN
7                  NaN
8          Crunchyroll
9               Nenhum
10                 HBO
11              Nenhum
12         Disney Plus
13               Todos
14                 NaN
15    Netflix e Disney
16                 NaN
17                 NaN
18                 NaN
19          Globo Play
20                 NaN
21              Nenhum
22                 NaN
23              Nenhum
24         Disney Plus
25                 NaN
26                 NaN
27                 NaN
28             Netflix
29               Todos
30          Globo Play
31                 HBO
32                 HBO
33                 NaN
34                 NaN
35          Globo Play
36         Crunchyroll
Name: Streaming, dtype: object

In [55]:
#substituindo os dados na coluna Streaming que contem separador 'e'
df_hillo_stream = df_hillo['Streaming'].str.get_dummies(sep=' e ')
#df_hillo.Streaming = df_hillo.Streaming.replace({'Todos': 'Globo Play e Netflix e HBO e Disney Plus e Crunchyroll'})

In [52]:
#Criando uma nova substituicao = todos passa a ser 
df_hillo.Streaming = df_hillo.Streaming.replace({'Todos': 'Globo Play e Netflix e HBO e Disney Plus e Crunchyroll'})

In [53]:
df_hillo.Streaming = df_hillo.Streaming.replace({'Netflix e Disney':'Netflix e Disney Plus' })

In [ ]:
df_hillo_stream = df_hillo['Streaming'].str.get_dummies(sep=' e ')

In [ ]:
#unindo dados com o metodo concact
#concatenando os valores a tabela  df_hillo a tabela  df_hillo_stream, a partir do axis=1, que representa a coluna
df_hillo = pd.concat([df_hillo, df_hillo_stream], axis=1)
df_hillo.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,N Filhos,Streaming,...,Globo Play,HBO,Nenhum,Netflix,Crunchyroll,Disney Plus,Globo Play,HBO,Nenhum,Netflix
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Globo Play,...,1,0,0,0,0,0,1,0,0,0
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,Globo Play e Netflix e HBO e Disney Plus e Cru...,...,1,1,0,1,1,1,1,1,0,1
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,NaN,...,0,0,0,0,0,0,0,0,0,0
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Globo Play,...,1,0,0,0,0,0,1,0,0,0

Cenário 3: Uma influenciadora digital de bem estar gostaria de analisar possíveis empreendimentos dentro de diferentes propostas que recebe. Essas propostas podem ser excludentes ou somatórias.

In [91]:
df.columns

Index(['Nome', 'Endereço', 'Cidade', 'Estado', 'Telefone', 'Renda Anual',
       'Estado Civil', 'Idade', 'N Filhos', 'Moradia', 'Restrição alimentar',
       'Streaming', 'Usa protetor solar diariamente',
       'Vai na Praia Mensalmente', 'Faz Academia',
       'Compra e Lê Livros Todos os Anos', 'Quantidade de Livros Comprados',
       'Autor Favorito', 'email'],
      dtype='object')

In [92]:
#copiando as colunas para a variavel df_info
df_inf =df.copy()

#excluindo colunas que não são interessantes para análise
df_inf = df_inf.drop(columns=['Streaming', 'Moradia' ])

In [96]:
#conferindo dados na coluna 'Restrição alimentar'
df_inf['Restrição alimentar']

0              Nenhuma
1                  NaN
2     Lactose e Glúten
3     Lactose e Glúten
4                  NaN
5                  NaN
6              Lactose
7              Nenhuma
8              Nenhuma
9              Lactose
10             Nenhuma
11             Lactose
12              Glúten
13                 NaN
14              Glúten
15                 NaN
16    Lactose e Glúten
17    Lactose e Glúten
18    Lactose e Glúten
19                 NaN
20                 NaN
21                 NaN
22             Nenhuma
23             Nenhuma
24                 NaN
25                 NaN
26              Glúten
27              Glúten
28             Nenhuma
29             Nenhuma
30    Lactose e Glúten
31             Lactose
32    Lactose e Glúten
33                 NaN
34                 NaN
35             Nenhuma
36                 NaN
Name: Restrição alimentar, dtype: object

In [ ]:
#criando a variavel df_inf para analisar a coluna Restrição alimentar e criar duas colunas a partir do separador comum'e '.Dpeois Dropando coluna nenuma 
#df_inf.head()
resticao = df_inf['Restrição alimentar'].str.get_dummies(sep= ' e ').drop(columns=['Nenhuma'])

In [ ]:
#inserindo as novas colunas Gluten e Lactose na tabela principa (df_inf_)
df_inf = pd.concat([df_inf, resticao], axis=1)
df_inf.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,N Filhos,Restrição alimentar,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email,Glúten,Lactose
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Nenhuma,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com,0,0
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,NaN,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com,0,0
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Lactose e Glúten,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com,1,1
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Lactose e Glúten,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com,1,1
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,NaN,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com,0,0